name: smart_alarm_app
description: A smart alarm app with cognitive wake-up challenges.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  android_intent_plus: ^4.0.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.2.1
  workmanager: ^0.6.0
  http: ^1.2.0
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
